//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zoo.imp
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int id { get; set; }
        public int idEmployee { get; set; }
        public int idAnimal { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual animal animal { get; set; }
        public virtual employee employee { get; set; }
    }
}
